name: Update README with Markscribe + WakaTime

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # every 6 hours (adjust as you want)
  workflow_dispatch:

jobs:
  markscribe:
    permissions:
      contents: write  # Required for git-auto-commit-action to push changes
    runs-on: ubuntu-latest

    steps:
      - name: Generate README
        uses: muesli/readme-scribe@master
        env:

        with:
          template: 'README.gtpl'
          writeTo: 'README.md'

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: 'markscribe: update README.md'