name: markscribe

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"  # Every hour

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # or latest stable

      - name: Clone markscribe fork
        run: git clone https://github.com/TaciturnAxolotl/markscribe.git

      - name: Build markscribe
        run: |
          cd markscribe
          go build -o markscribe .

      - name: Generate README with markscribe fork
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          ./markscribe/markscribe -entry ../README.gtpl -write README.md

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'markscribe: update README.md'
