name: Update README with Markscribe + WakaTime

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours (adjust as you want)
  workflow_dispatch:

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Clone TaciturnAxolotl markscribe fork
        run: git clone https://github.com/TaciturnAxolotl/markscribe.git

      - name: Build markscribe
        run: |
          cd markscribe
          go build -o ../markscribe-bin .

      - name: Generate README using markscribe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          ./markscribe-bin -entry README.gtpl -write README.md

      - name: Commit and push README.md changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "markscribe: update README.md"
        env:
          GITHUB_TOKEN: ${{ github.token }}
