name: markscribe

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"  # every hour

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate README with WakaTime
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          template: 'README.gtpl'
          writeTo: 'README.md'
          wakaTimeUsername: your-wakatime-username

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'markscribe: update README.md'
